spring.cloud.stream.bindings.output.contentType: application/json
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams.binder.configuration:
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings.output:
  destination: counts
  producer:
    headerMode: raw
    #useNativeEncoding: true
spring.cloud.stream.bindings.input:
  destination: words
  consumer:
    headerMode: raw
#For testing
spring.cloud.stream.bindings.input1.destination: counts
spring.cloud.stream.bindings.output1.destination: words
spring.cloud.stream.bindings.input1.binder: kafka
spring.cloud.stream.bindings.output1.binder: kafka



